#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : zict
Version  : 0.1.3
Release  : 3
URL      : https://files.pythonhosted.org/packages/f2/a6/e1ccbb86f7d6dcaa545623f0c0ee1984697869e3c6a5d43bb6398616b389/zict-0.1.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/f2/a6/e1ccbb86f7d6dcaa545623f0c0ee1984697869e3c6a5d43bb6398616b389/zict-0.1.3.tar.gz
Summary  : Mutable mapping tools
Group    : Development/Tools
License  : BSD-3-Clause
Requires: zict-license = %{version}-%{release}
Requires: zict-python = %{version}-%{release}
Requires: zict-python3 = %{version}-%{release}
Requires: HeapDict
BuildRequires : buildreq-distutils3

%description
Zict
====
|Build Status|
Mutable Mapping interfaces.  See documentation_.
.. _documentation: http://zict.readthedocs.io/en/latest/
.. |Build Status| image:: https://travis-ci.org/dask/zict.svg?branch=master
:target: https://travis-ci.org/dask/zict

%package license
Summary: license components for the zict package.
Group: Default

%description license
license components for the zict package.


%package python
Summary: python components for the zict package.
Group: Default
Requires: zict-python3 = %{version}-%{release}

%description python
python components for the zict package.


%package python3
Summary: python3 components for the zict package.
Group: Default
Requires: python3-core

%description python3
python3 components for the zict package.


%prep
%setup -q -n zict-0.1.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551152399
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/zict
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/zict/LICENSE.txt
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/zict/LICENSE.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
